### ISSUE TITLE
How to use with dynamic content?

### ISSUE THREAD

**Issue by theaqua** [henriquea/minigrid#16]
First, thanks for this library!
How to use it with dynamic content? For example, with images.

http://jsbin.com/tudevubive/edit?html,css,output

**Comment by Mustafaoeztuerk** [comment]
I think you need to use CSS for image. like .grid-item img {width:100%;}

**Comment by henriquea** [comment]
@Mustafaoeztuerk not really 😀

@theaqua because you're loading images asynchronously you do need a lazy loading. I did a simple example here http://output.jsbin.com/ladilo

Note the `display: inline-block` in the `.grid-item` for this case where the content is dynamic.

Finally the last thing to note is that Minigrid won't work well with different width sizes. This is something I'm going to add to its documentation. I did this having in mind "cards" with equal widths but different heights. For anything else I'd recommend [Isotope](http://isotope.metafizzy.co/).

**Comment by Mustafaoeztuerk** [comment]
hmmm yeah I saw. I didn't look at carefully.

**Comment by henriquea** [comment]
@Mustafaoeztuerk no worries 😊

**Comment by Mustafaoeztuerk** [comment]
@henriquea  can you check my issue for me ?

**Comment by theaqua** [comment]
@henriquea thanks!
