### ISSUE TITLE
Append items to grid without recalculate the whole grid again.

### ISSUE THREAD

**Issue by kilianso** [henriquea/minigrid#52]
Hey there, minigrid.js is great and i really love it! It's light, fast and just does what i should. I have just one question: Is there an "append" method or similar? Because if i want to add more items by Ajax the whole grid function is fired and all the items are recalculated, which is a performance hit. And i really need to extend the already visible grid instead of pagination or something. Any hints or an example would be great.

**Comment by henriquea** [comment]
Hey @kilianso thanks for the nice words!

I know this may sound simple but we'd need to know which items are new and move the position only for those. I'm not sure if worth effort since the idea is to keep it simple. Regarding performance I completely agree that re-render the grid is a bad idea. If I were to write this library today I'd probably use shadowDOM. 

If you need more power have a look at [Isotope](http://isotope.metafizzy.co) or consider using React to get all the goodies of the virtual DOM and state.

I'll close this issue but please feel free to comment or ask anything else here 😊
